import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <h1>Header</h1>
        <div>
          <Link href="/">Home</Link>|
          <Link href="/about">About</Link>|
          <Link href="/contact">Contact</Link>
        </div>
        <hr />
        {children}
        <hr />
        <h2>Footer</h2>
      </body>
    </html>
  );
}